### PR TITLE
[FEAT/FIX] Added a new instance of storage loader for each year

### LINKED ISSUE #63: Create a new instance of MoodleBooster's data in the localstorage each year.
## What?

"MoodleBooster" uses the localStorage in order to save its state.
In the localStorage we save the current font size, if we are in dark-mode or not, the numbers of the removed courses and if we are in monochrome mode.
**This bug is a performance bug since the way we eliminate courses from the navigation bar is by iterating over the removed courses that are in the localStorage, if we will create a new instance for each year we will have much less items to iterate.**

## Current Behavior

We save the state of the user once for all of the year.

## Expected Behavior

Save new localStorage "MoodleBooster" instance for each year.

### PR DESCRIPTION
**Pull request by norbit8**
## Fixed:

Added a new instance of storage loader for each year
Please reference this (#63) issue for the full details.

## Image from the Local-Storage:
Screen Shot 2021-06-25 at 23 16 48

### CODE REVIEW

File: content_scripts/storageLoader.js [hunk 1]
```diff
@@ -235,10 +236,10 @@ async function loadSave() {
      *  if it doesn't then it creates one)
      * and then it initialize the page according to the instructions given in the loaded settings.
      */
-    var moodleBoosterData = localStorage.getItem('MoodleBooster');   // Load MoodleBooster's data from the localStorage
+    var moodleBoosterData = localStorage.getItem('MoodleBooster' + currentYear);   // Load MoodleBooster's data from the localStorage
```
Comment (idan2468) [inline content_scripts/storageLoader.js:243]: Please add error handling for a situation that the currentYear not found.
I think of just putting the key 'MoodleBooster'

**Review by idan2468 — CHANGES_REQUESTED** [review]
Please see the comment :)

**Review by idan2468 — APPROVED** [review]
Great
